### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by uniconstructor** [rackerlabs/atom-cloud-sync#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [cloud-sync](https://github.com/rackerlabs/atom-cloud-sync) package, v0.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/frost/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/frost/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:4:199)
  at /Users/frost/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:5:3
  at Object.<anonymous> (/Users/frost/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:52:5)
  at Object.<anonymous> (/Users/frost/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/frost/.atom/packages/cloud-sync/lib/cloud-sync.coffee:1:17)
  at Object.<anonymous> (/Users/frost/.atom/packages/cloud-sync/lib/cloud-sync.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -4:32 settings-view:uninstall-packages (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:47.1.0 core:paste (atom-text-editor#gist-it.userToken.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "atom-beautify"
    ],
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/frosr/git"
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-html-preview, v0.1.8
autocomplete-php, v0.3.6
build, v0.38.0
codeception-snippets, v0.1.0
color-picker, v2.0.7
git-diff-details, v0.18.0
git-log, v0.4.1
git-projects, v1.14.1
jenkins, v0.3.4
keycodes, v0.1.4
language-mongodb, v0.2.0
meteor-api, v2.19.0
minimap, v4.10.0
my-github-profile, v0.2.0
nuclide-installer, v0.0.22
php-introspector, v1.0.0
phpunit, v1.1.1
svn, v0.0.6
tree-view-git-modified, v0.5.10
tree-view-git-projects, v0.5.0
tualo-git-context, v0.6.10

# Dev
No dev packages
```

**Comment by amonks** [comment]
I got the same issue while trying to install the package

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [cloud-sync](https://github.com/rackerlabs/atom-cloud-sync) package, v0.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:4:199)
  at /Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:5:3
  at Object.<anonymous> (/Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:52:5)
  at Object.<anonymous> (/Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync.coffee:1:17)
  at Object.<anonymous> (/Users/ajm/.atom/packages/cloud-sync/lib/cloud-sync.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at Package.module.exports.Package.activateConfig (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:150:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:187:12)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:232:24
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:587:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:378:26
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:07.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -1:07.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:05.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:05.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:04.1.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:29.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:06.6.0 settings-view:open (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
autoclose-html, v0.18.0
color-picker, v2.0.11
minimap, v4.12.1
vim-mode, v0.57.0

# Dev
No dev packages
```
