### ISSUE TITLE
Failed to load the cloud-sync package

### ISSUE THREAD

**Issue by lizardd** [rackerlabs/atom-cloud-sync#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [cloud-sync](https://github.com/rackerlabs/atom-cloud-sync) package, v0.0.2

### Stack Trace

Failed to load the cloud-sync package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\Administrator\.atom\packages\cloud-sync\lib\cloud-sync-view.coffee:4:199)
    at C:\Users\Administrator\.atom\packages\cloud-sync\lib\cloud-sync-view.coffee:9:5
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\cloud-sync\lib\cloud-sync-view.coffee:52:5)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\cloud-sync\lib\cloud-sync-view.coffee:54:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ConvertToUtf8Plus"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
cloud-sync, v0.0.2
emmet, v2.3.12
language-ejs, v0.2.0

# Dev
No dev packages
```

**Comment by dhinakg** [comment]
I have this too. Anyone?

**Comment by dougmorin** [comment]
Is there any solution for this?

**Comment by nicdesjardins** [comment]
I had the same issue here, tagging myself... Will I get alerted once an issue is resolved if I've joined in on the discussion?

**Comment by kid1carus** [comment]
[This is the error I received.](https://pastebin.com/R4cHMTu1)  Im guessing there is no fix for it yet?

**Comment by williamortiz** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [cloud-sync](https://github.com/rackerlabs/atom-cloud-sync) package 0.0.2


### Stack Trace

Failed to load the cloud-sync package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/cloud-sync/lib/cloud-sync-view.coffee:1:1)
    at /packages/cloud-sync/lib/cloud-sync-view.coffee:4:7
    at /packages/cloud-sync/lib/cloud-sync-view.coffee:19:11)
    at /packages/cloud-sync/lib/cloud-sync-view.coffee:1:1)
    at /packages/cloud-sync/lib/cloud-sync-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/cloud-sync/lib/cloud-sync.coffee:1:17)
    at /packages/cloud-sync/lib/cloud-sync.coffee:1:1)
    at /packages/cloud-sync/lib/cloud-sync.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3233575)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3220115)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3218947)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3219688)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381026)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379449)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331514)
```

### Commands

```
```

### Non-Core Packages

```
cloud-sync 0.0.2 
```
